spring.application.name=DUO
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# --- CONFIGURAÇÃO NOVA (QuizAPI) ---
# A URL oficial para pegar perguntas de programação (Linux, Code, Docker, etc)
quizapi.url=https://quizapi.io/api/v1/questions
# A chave que você mandou
quizapi.key=7MIpPscFVj9ANPTOWlwrBGcOZsJMaIcLitjP26XN