spring.application.name=DUO
server.port=8081
# Configuração do Gemini
gemini.api.key= AIzaSyBDZ3oEjhAgUP8LAjbZSJariNO4447RF_8
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent