spring.application.name=DUO
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

gemini.api.key=AIzaSyCfWB_aEPzGqEyH27Dcc0njDUS85xbt_s4
gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent